GCC = g++
Flags = -Werror -std=c++17

VowelCorrector: VowelCorrector.o
	$(GCC) $(Flags) -o VowelCorrector VowelCorrector.o

VowelCorrector.o: VowelCorrector.cpp
	$(GCC) $(Flags) -c VowelCorrector.cpp
	
